use enigo::{Axis, Button, Coordinate, Key};

pub fn get_mouse_button_by_index(index: i32) -> Button {
    match index {
        1 => Button::Left,
        3 => Button::Middle,
        2 => Button::Right,
        4 => Button::Back,
        5 => Button::Forward,
        6 => Button::ScrollUp,
        7 => Button::ScrollDown,
        8 => Button::ScrollLeft,
        9 => Button::ScrollRight,
        _ => Button::Left,
    }
}

pub fn get_direction_by_index(index: i32) -> enigo::Direction {
    match index {
        0 => enigo::Direction::Press,
        1 => enigo::Direction::Release,
        3 => enigo::Direction::Click,
        _ => enigo::Direction::Press,
    }
}

pub fn get_coordinate_by_index(index: i32) -> Coordinate {
    match index {
        0 => Coordinate::Abs,
        1 => Coordinate::Rel,
        _ => Coordinate::Abs,
    }
}

pub fn get_axis_by_index(index: i32) -> Axis {
    match index {
        0 => Axis::Horizontal,
        1 => Axis::Vertical,
        _ => Axis::Vertical,
    }
}

pub fn get_key_by_index(index: i32) -> Key {
    match index {
        #[cfg(target_os = "windows")]
        0 => Key::Num0,
        #[cfg(target_os = "windows")]
        1 => Key::Num1,
        #[cfg(target_os = "windows")]
        2 => Key::Num2,
        #[cfg(target_os = "windows")]
        3 => Key::Num3,
        #[cfg(target_os = "windows")]
        4 => Key::Num4,
        #[cfg(target_os = "windows")]
        5 => Key::Num5,
        #[cfg(target_os = "windows")]
        6 => Key::Num6,
        #[cfg(target_os = "windows")]
        7 => Key::Num7,
        #[cfg(target_os = "windows")]
        8 => Key::Num8,
        #[cfg(target_os = "windows")]
        9 => Key::Num9,
        #[cfg(target_os = "windows")]
        10 => Key::A,
        #[cfg(target_os = "windows")]
        11 => Key::B,
        #[cfg(target_os = "windows")]
        12 => Key::C,
        #[cfg(target_os = "windows")]
        13 => Key::D,
        #[cfg(target_os = "windows")]
        14 => Key::E,
        #[cfg(target_os = "windows")]
        15 => Key::F,
        #[cfg(target_os = "windows")]
        16 => Key::G,
        #[cfg(target_os = "windows")]
        17 => Key::H,
        #[cfg(target_os = "windows")]
        18 => Key::I,
        #[cfg(target_os = "windows")]
        19 => Key::J,
        #[cfg(target_os = "windows")]
        20 => Key::K,
        #[cfg(target_os = "windows")]
        21 => Key::L,
        #[cfg(target_os = "windows")]
        22 => Key::M,
        #[cfg(target_os = "windows")]
        23 => Key::N,
        #[cfg(target_os = "windows")]
        24 => Key::O,
        #[cfg(target_os = "windows")]
        25 => Key::P,
        #[cfg(target_os = "windows")]
        26 => Key::Q,
        #[cfg(target_os = "windows")]
        27 => Key::R,
        #[cfg(target_os = "windows")]
        28 => Key::S,
        #[cfg(target_os = "windows")]
        29 => Key::T,
        #[cfg(target_os = "windows")]
        30 => Key::U,
        #[cfg(target_os = "windows")]
        31 => Key::V,
        #[cfg(target_os = "windows")]
        32 => Key::W,
        #[cfg(target_os = "windows")]
        33 => Key::X,
        #[cfg(target_os = "windows")]
        34 => Key::Y,
        #[cfg(target_os = "windows")]
        35 => Key::Z,
        #[cfg(target_os = "windows")]
        36 => Key::AbntC1,
        #[cfg(target_os = "windows")]
        37 => Key::AbntC2,
        #[cfg(target_os = "windows")]
        38 => Key::Accept,
        39 => Key::Add,
        40 => Key::Alt, // alt key on Linux and Windows (option key on macOS)
        #[cfg(target_os = "windows")]
        41 => Key::Apps,
        #[cfg(target_os = "windows")]
        42 => Key::Attn,
        43 => Key::Backspace, // backspace key
        #[cfg(all(unix, not(target_os = "macos")))]
        44 => Key::Break,
        #[cfg(all(unix, not(target_os = "macos")))]
        45 => Key::Begin,
        #[cfg(target_os = "macos")]
        46 => Key::BrightnessDown,
        #[cfg(target_os = "macos")]
        47 => Key::BrightnessUp,
        #[cfg(target_os = "windows")]
        48 => Key::BrowserBack,
        #[cfg(target_os = "windows")]
        49 => Key::BrowserFavorites,
        #[cfg(target_os = "windows")]
        50 => Key::BrowserForward,
        #[cfg(target_os = "windows")]
        51 => Key::BrowserHome,
        #[cfg(target_os = "windows")]
        52 => Key::BrowserRefresh,
        #[cfg(target_os = "windows")]
        53 => Key::BrowserSearch,
        #[cfg(target_os = "windows")]
        54 => Key::BrowserStop,
        #[cfg(any(target_os = "windows", all(unix, not(target_os = "macos"))))]
        55 => Key::Cancel,
        56 => Key::CapsLock, // caps lock key
        #[cfg(any(target_os = "windows", all(unix, not(target_os = "macos"))))]
        57 => Key::Clear,
        #[deprecated(since = "0.0.12", note = "now renamed to Meta")]
        #[cfg_attr(feature = "serde", serde(alias = "cmd"))]
        58 => Key::Command, // command key on macOS (super key on Linux, windows key on Windows)
        #[cfg(target_os = "macos")]
        59 => Key::ContrastUp,
        #[cfg(target_os = "macos")]
        60 => Key::ContrastDown,
        61 => Key::Control, // control key
        #[cfg_attr(feature = "serde", serde(alias = "ctrl"))]
        62 => Key::Control,
        #[cfg(target_os = "windows")]
        63 => Key::Convert,
        #[cfg(target_os = "windows")]
        64 => Key::Crsel,
        #[cfg(target_os = "windows")]
        65 => Key::DBEAlphanumeric,
        #[cfg(target_os = "windows")]
        66 => Key::DBECodeinput,
        #[cfg(target_os = "windows")]
        67 => Key::DBEDetermineString,
        #[cfg(target_os = "windows")]
        68 => Key::DBEEnterDLGConversionMode,
        #[cfg(target_os = "windows")]
        69 => Key::DBEEnterIMEConfigMode,
        #[cfg(target_os = "windows")]
        70 => Key::DBEEnterWordRegisterMode,
        #[cfg(target_os = "windows")]
        71 => Key::DBEFlushString,
        #[cfg(target_os = "windows")]
        72 => Key::DBEHiragana,
        #[cfg(target_os = "windows")]
        73 => Key::DBEKatakana,
        #[cfg(target_os = "windows")]
        74 => Key::DBENoCodepoint,
        #[cfg(target_os = "windows")]
        75 => Key::DBENoRoman,
        #[cfg(target_os = "windows")]
        76 => Key::DBERoman,
        #[cfg(target_os = "windows")]
        77 => Key::DBESBCSChar,
        #[cfg(target_os = "windows")]
        78 => Key::DBESChar,
        79 => Key::Decimal,
        80 => Key::Delete, // delete key
        81 => Key::Divide,
        82 => Key::DownArrow, // down arrow key
        #[cfg(target_os = "macos")]
        83 => Key::Eject,
        84 => Key::End, // end key
        #[cfg(target_os = "windows")]
        85 => Key::Ereof,
        86 => Key::Escape, // escape key (esc)
        #[cfg(any(target_os = "windows", all(unix, not(target_os = "macos"))))]
        87 => Key::Execute,
        #[cfg(target_os = "windows")]
        88 => Key::Exsel,
        89 => Key::F1,   // F1 key
        90 => Key::F2,   // F2 key
        91 => Key::F3,   // F3 key
        92 => Key::F4,   // F4 key
        93 => Key::F5,   // F5 key
        94 => Key::F6,   // F6 key
        95 => Key::F7,   // F7 key
        96 => Key::F8,   // F8 key
        97 => Key::F9,   // F9 key
        98 => Key::F10,  // F10 key
        99 => Key::F11,  // F11 key
        100 => Key::F12, // F12 key
        101 => Key::F13, // F13 key
        102 => Key::F14, // F14 key
        103 => Key::F15, // F15 key
        104 => Key::F16, // F16 key
        105 => Key::F17, // F17 key
        106 => Key::F18, // F18 key
        107 => Key::F19, // F19 key
        108 => Key::F20, // F20 key
        #[cfg(any(target_os = "windows", all(unix, not(target_os = "macos"))))]
        109 => Key::F21, // F21 key
        #[cfg(any(target_os = "windows", all(unix, not(target_os = "macos"))))]
        110 => Key::F22, // F22 key
        #[cfg(any(target_os = "windows", all(unix, not(target_os = "macos"))))]
        111 => Key::F23, // F23 key
        #[cfg(any(target_os = "windows", all(unix, not(target_os = "macos"))))]
        112 => Key::F24, // F24 key
        #[cfg(all(unix, not(target_os = "macos")))]
        113 => Key::F25,
        #[cfg(all(unix, not(target_os = "macos")))]
        114 => Key::F26,
        #[cfg(all(unix, not(target_os = "macos")))]
        115 => Key::F27,
        #[cfg(all(unix, not(target_os = "macos")))]
        116 => Key::F28,
        #[cfg(all(unix, not(target_os = "macos")))]
        117 => Key::F29,
        #[cfg(all(unix, not(target_os = "macos")))]
        118 => Key::F30,
        #[cfg(all(unix, not(target_os = "macos")))]
        119 => Key::F31,
        #[cfg(all(unix, not(target_os = "macos")))]
        120 => Key::F32,
        #[cfg(all(unix, not(target_os = "macos")))]
        121 => Key::F33,
        #[cfg(all(unix, not(target_os = "macos")))]
        122 => Key::F34,
        #[cfg(all(unix, not(target_os = "macos")))]
        123 => Key::F35,
        #[cfg(target_os = "macos")]
        124 => Key::Function,
        #[cfg(target_os = "windows")]
        125 => Key::Final,
        #[cfg(all(unix, not(target_os = "macos")))]
        126 => Key::Find,
        #[cfg(target_os = "windows")]
        127 => Key::GamepadA,
        #[cfg(target_os = "windows")]
        128 => Key::GamepadB,
        #[cfg(target_os = "windows")]
        129 => Key::GamepadDPadDown,
        #[cfg(target_os = "windows")]
        130 => Key::GamepadDPadLeft,
        #[cfg(target_os = "windows")]
        131 => Key::GamepadDPadRight,
        #[cfg(target_os = "windows")]
        132 => Key::GamepadDPadUp,
        #[cfg(target_os = "windows")]
        133 => Key::GamepadLeftShoulder,
        #[cfg(target_os = "windows")]
        134 => Key::GamepadLeftThumbstickButton,
        #[cfg(target_os = "windows")]
        135 => Key::GamepadLeftThumbstickDown,
        #[cfg(target_os = "windows")]
        136 => Key::GamepadLeftThumbstickLeft,
        #[cfg(target_os = "windows")]
        137 => Key::GamepadLeftThumbstickRight,
        #[cfg(target_os = "windows")]
        138 => Key::GamepadLeftThumbstickUp,
        #[cfg(target_os = "windows")]
        139 => Key::GamepadLeftTrigger,
        #[cfg(target_os = "windows")]
        140 => Key::GamepadMenu,
        #[cfg(target_os = "windows")]
        141 => Key::GamepadRightShoulder,
        #[cfg(target_os = "windows")]
        142 => Key::GamepadRightThumbstickButton,
        #[cfg(target_os = "windows")]
        143 => Key::GamepadRightThumbstickDown,
        #[cfg(target_os = "windows")]
        144 => Key::GamepadRightThumbstickLeft,
        #[cfg(target_os = "windows")]
        145 => Key::GamepadRightThumbstickRight,
        #[cfg(target_os = "windows")]
        146 => Key::GamepadRightThumbstickUp,
        #[cfg(target_os = "windows")]
        147 => Key::GamepadRightTrigger,
        #[cfg(target_os = "windows")]
        148 => Key::GamepadView,
        #[cfg(target_os = "windows")]
        149 => Key::GamepadX,
        #[cfg(target_os = "windows")]
        150 => Key::GamepadY,
        #[cfg(target_os = "windows")]
        151 => Key::Hangeul,
        #[cfg(any(target_os = "windows", all(unix, not(target_os = "macos"))))]
        152 => Key::Hangul,
        #[cfg(any(target_os = "windows", all(unix, not(target_os = "macos"))))]
        153 => Key::Hanja,
        154 => Key::Help,
        155 => Key::Home, // home key
        #[cfg(target_os = "windows")]
        156 => Key::Ico00,
        #[cfg(target_os = "windows")]
        157 => Key::IcoClear,
        #[cfg(target_os = "windows")]
        158 => Key::IcoHelp,
        #[cfg(target_os = "macos")]
        159 => Key::IlluminationDown,
        #[cfg(target_os = "macos")]
        160 => Key::IlluminationUp,
        #[cfg(target_os = "macos")]
        161 => Key::IlluminationToggle,
        #[cfg(target_os = "windows")]
        162 => Key::IMEOff,
        #[cfg(target_os = "windows")]
        163 => Key::IMEOn,
        #[cfg(any(target_os = "windows", all(unix, not(target_os = "macos"))))]
        164 => Key::Insert,
        #[cfg(target_os = "windows")]
        165 => Key::Junja,
        #[cfg(target_os = "windows")]
        166 => Key::Kana,
        #[cfg(any(target_os = "windows", all(unix, not(target_os = "macos"))))]
        167 => Key::Kanji,
        #[cfg(target_os = "windows")]
        168 => Key::LaunchApp1,
        #[cfg(target_os = "windows")]
        169 => Key::LaunchApp2,
        #[cfg(target_os = "windows")]
        170 => Key::LaunchMail,
        #[cfg(target_os = "windows")]
        171 => Key::LaunchMediaSelect,
        #[cfg(target_os = "macos")]
        172 => Key::Launchpad, // Opens launchpad
        #[cfg(target_os = "macos")]
        173 => Key::LaunchPanel,
        #[cfg(target_os = "windows")]
        174 => Key::LButton,
        175 => Key::LControl,
        176 => Key::LeftArrow, // left arrow key
        #[cfg(all(unix, not(target_os = "macos")))]
        177 => Key::Linefeed,
        #[cfg(any(target_os = "windows", all(unix, not(target_os = "macos"))))]
        178 => Key::LMenu,
        179 => Key::LShift,
        #[cfg(target_os = "windows")]
        180 => Key::LWin,
        #[cfg(target_os = "windows")]
        181 => Key::MButton,
        #[cfg(target_os = "macos")]
        182 => Key::MediaFast,
        183 => Key::MediaNextTrack,
        184 => Key::MediaPlayPause,
        185 => Key::MediaPrevTrack,
        #[cfg(target_os = "macos")]
        186 => Key::MediaRewind,
        #[cfg(any(target_os = "windows", all(unix, not(target_os = "macos"))))]
        187 => Key::MediaStop,
        188 => Key::Meta,
        #[cfg(target_os = "macos")]
        189 => Key::MissionControl,
        #[cfg(any(target_os = "windows", all(unix, not(target_os = "macos"))))]
        190 => Key::ModeChange,
        191 => Key::Multiply,
        #[cfg(target_os = "windows")]
        192 => Key::NavigationAccept,
        #[cfg(target_os = "windows")]
        193 => Key::NavigationCancel,
        #[cfg(target_os = "windows")]
        194 => Key::NavigationDown,
        #[cfg(target_os = "windows")]
        195 => Key::NavigationLeft,
        #[cfg(target_os = "windows")]
        196 => Key::NavigationMenu,
        #[cfg(target_os = "windows")]
        197 => Key::NavigationRight,
        #[cfg(target_os = "windows")]
        198 => Key::NavigationUp,
        #[cfg(target_os = "windows")]
        199 => Key::NavigationView,
        #[cfg(target_os = "windows")]
        200 => Key::NoName,
        #[cfg(target_os = "windows")]
        201 => Key::NonConvert,
        #[cfg(target_os = "windows")]
        202 => Key::None,
        #[cfg(any(target_os = "windows", all(unix, not(target_os = "macos"))))]
        203 => Key::Numlock,
        204 => Key::Numpad0,
        205 => Key::Numpad1,
        206 => Key::Numpad2,
        207 => Key::Numpad3,
        208 => Key::Numpad4,
        209 => Key::Numpad5,
        210 => Key::Numpad6,
        211 => Key::Numpad7,
        212 => Key::Numpad8,
        213 => Key::Numpad9,
        #[cfg(target_os = "windows")]
        214 => Key::OEM1,
        #[cfg(target_os = "windows")]
        215 => Key::OEM102,
        #[cfg(target_os = "windows")]
        216 => Key::OEM2,
        #[cfg(target_os = "windows")]
        217 => Key::OEM3,
        #[cfg(target_os = "windows")]
        218 => Key::OEM4,
        #[cfg(target_os = "windows")]
        219 => Key::OEM5,
        #[cfg(target_os = "windows")]
        220 => Key::OEM6,
        #[cfg(target_os = "windows")]
        221 => Key::OEM7,
        #[cfg(target_os = "windows")]
        222 => Key::OEM8,
        #[cfg(target_os = "windows")]
        223 => Key::OEMAttn,
        #[cfg(target_os = "windows")]
        224 => Key::OEMAuto,
        #[cfg(target_os = "windows")]
        225 => Key::OEMAx,
        #[cfg(target_os = "windows")]
        226 => Key::OEMBacktab,
        #[cfg(target_os = "windows")]
        227 => Key::OEMClear,
        #[cfg(target_os = "windows")]
        228 => Key::OEMComma,
        #[cfg(target_os = "windows")]
        229 => Key::OEMCopy,
        #[cfg(target_os = "windows")]
        230 => Key::OEMCusel,
        #[cfg(target_os = "windows")]
        231 => Key::OEMEnlw,
        #[cfg(target_os = "windows")]
        232 => Key::OEMFinish,
        #[cfg(target_os = "windows")]
        233 => Key::OEMFJJisho,
        #[cfg(target_os = "windows")]
        234 => Key::OEMFJLoya,
        #[cfg(target_os = "windows")]
        235 => Key::OEMFJMasshou,
        #[cfg(target_os = "windows")]
        236 => Key::OEMFJRoya,
        #[cfg(target_os = "windows")]
        237 => Key::OEMFJTouroku,
        #[cfg(target_os = "windows")]
        238 => Key::OEMJump,
        #[cfg(target_os = "windows")]
        239 => Key::OEMMinus,
        #[cfg(target_os = "windows")]
        240 => Key::OEMNECEqual,
        #[cfg(target_os = "windows")]
        241 => Key::OEMPA1,
        #[cfg(target_os = "windows")]
        242 => Key::OEMPA2,
        #[cfg(target_os = "windows")]
        243 => Key::OEMPA3,
        #[cfg(target_os = "windows")]
        244 => Key::OEMPeriod,
        #[cfg(target_os = "windows")]
        245 => Key::OEMPlus,
        #[cfg(target_os = "windows")]
        246 => Key::OEMReset,
        #[cfg(target_os = "windows")]
        247 => Key::OEMWsctrl,
        248 => Key::Option,
        #[cfg(target_os = "windows")]
        249 => Key::PA1,
        #[cfg(target_os = "windows")]
        250 => Key::Packet,
        251 => Key::PageDown,
        252 => Key::PageUp,
        #[cfg(any(target_os = "windows", all(unix, not(target_os = "macos"))))]
        253 => Key::Pause,
        #[cfg(target_os = "windows")]
        254 => Key::Play,
        #[cfg(target_os = "macos")]
        255 => Key::Power,
        #[cfg(any(target_os = "windows", all(unix, not(target_os = "macos"))))]
        256 => Key::Print,
        #[cfg(any(target_os = "windows", all(unix, not(target_os = "macos"))))]
        257 => Key::PrintScr,
        #[cfg(target_os = "windows")]
        258 => Key::Processkey,
        #[cfg(target_os = "windows")]
        259 => Key::RButton,
        #[cfg(target_os = "macos")]
        260 => Key::RCommand,
        261 => Key::RControl,
        #[cfg(all(unix, not(target_os = "macos")))]
        262 => Key::Redo,
        263 => Key::Return,
        264 => Key::RightArrow,
        #[cfg(target_os = "windows")]
        265 => Key::RMenu,
        #[cfg(target_os = "macos")]
        266 => Key::ROption,
        267 => Key::RShift,
        #[cfg(target_os = "windows")]
        268 => Key::RWin,
        #[cfg(target_os = "windows")]
        269 => Key::Scroll,
        #[cfg(all(unix, not(target_os = "macos")))]
        270 => Key::ScrollLock,
        #[cfg(any(target_os = "windows", all(unix, not(target_os = "macos"))))]
        271 => Key::Select,
        #[cfg(all(unix, not(target_os = "macos")))]
        272 => Key::ScriptSwitch,
        #[cfg(target_os = "windows")]
        273 => Key::Separator,
        274 => Key::Shift,
        #[cfg(all(unix, not(target_os = "macos")))]
        275 => Key::ShiftLock,
        #[cfg(target_os = "windows")]
        276 => Key::Sleep,
        #[cfg(target_os = "windows")]
        277 => Key::Snapshot,
        278 => Key::Space,
        279 => Key::Subtract,
        #[cfg(all(unix, not(target_os = "macos")))]
        280 => Key::SysReq,
        281 => Key::Tab,
        #[cfg(all(unix, not(target_os = "macos")))]
        282 => Key::Undo,
        283 => Key::UpArrow,
        #[cfg(target_os = "macos")]
        284 => Key::VidMirror,
        285 => Key::VolumeDown,
        286 => Key::VolumeMute,
        287 => Key::VolumeUp,
        #[cfg(all(unix, not(target_os = "macos")))]
        288 => Key::MicMute,
        #[cfg(target_os = "windows")]
        289 => Key::XButton1,
        #[cfg(target_os = "windows")]
        290 => Key::XButton2,
        #[cfg(target_os = "windows")]
        291 => Key::Zoom,
        292 => Key::Unicode('@'),
        293 => Key::Other(0),
        _ => Key::Other(0),
    }
}
