// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

void moveMouseAbsBase({required int x, required int y}) =>
    RustLib.instance.api.crateApiBixatKeyMouseMoveMouseAbsBase(x: x, y: y);

void moveMouseRelBase({required int x, required int y}) =>
    RustLib.instance.api.crateApiBixatKeyMouseMoveMouseRelBase(x: x, y: y);

void pressMouseButtonBase({required int button}) => RustLib.instance.api
    .crateApiBixatKeyMousePressMouseButtonBase(button: button);

void releaseMouseButtonBase({required int button}) => RustLib.instance.api
    .crateApiBixatKeyMouseReleaseMouseButtonBase(button: button);

void enterTextBase({required String text}) =>
    RustLib.instance.api.crateApiBixatKeyMouseEnterTextBase(text: text);

void simulateKeyBase({required String key}) =>
    RustLib.instance.api.crateApiBixatKeyMouseSimulateKeyBase(key: key);

void releaseKeyBase({required String key}) =>
    RustLib.instance.api.crateApiBixatKeyMouseReleaseKeyBase(key: key);
